### ISSUE TITLE
Cannot save whiteboard as image

### ISSUE THREAD

**Issue by homevk15** [cracker0dks/whiteboard#156]
The button "Save whiteboard as image" is not working, when I click this button nothing happens. Please, help me to fix it.

**Comment by cracker0dks** [comment]
Works without problem on my end. Wich OS and browser do you use?

**Comment by homevk15** [comment]
OS: Debian11
Browsers: Firefox ESR 91.13.0, Chrome version 106.0.5249.61.
Only "Save whiteboard as JSON" works good, the button "Save whiteboard as image" looks like deactivated on my side.

**Comment by cracker0dks** [comment]
that's odd we don't have a function build in that would disable only that button afaik. Can you inspect the element and see if it is really disabled per code?

**Comment by homevk15** [comment]
Seems like my browsers blocked pop-up windows. It works now.
Also I have a few ideas how to improve your application:
1.Let users to register in for Whiteboard. Show their nicknames at their pencils. It would be good to make this whiteboard as a WordPress plugin and log in users to Whiteboard automatically whenever they join a WordPress website.
2.Let users to create many instances of Whiteboard (one main whiteboard and a few draft whiteboards).
These would add more popularity for your application.
Thank you for helping me. Have a good time.

**Comment by cracker0dks** [comment]
Glad it is solved. 
Wordpress plugin is not working because we run nodejs and wordpress is written in php. You could could use a plugin that intigrates external sites into wordpress, like it is described for nextcloud in the doc.

Users already are able to create new whiteboards (just change the whiteboardid in the url). We dont have a good way to change the whiteboard besides changing the url
