### ISSUE TITLE
New feature: multipage support

### ISSUE THREAD

**Issue by tna76874** [cracker0dks/whiteboard#61]
The project meetzi.de has implemented some "multipage-thing". Of course you can everytime create a new whiteboard with another ID - but just opening another board in a session by clicking on something as "next page" would be awesome.

**Comment by varz29** [comment]
First of all thank you for building this amazing project @cracker0dks .
Opening multiple boards in a single page (session) would be really awesome.

**Comment by jolly-jump** [comment]
Hi @cracker0dks , I second this feature request.
I also wander, if there is some feature of scrolling the visible pane, since the one with the smallest screen will not be able to see how he/she is cybermobbed outside his/her visible pane :) 
Anyway: scrolling the pane would be an alternative to "multipage".

**Comment by cracker0dks** [comment]
we added a panning tool to the board.
