### ISSUE TITLE
Any documentations for integrating with Jitsi

### ISSUE THREAD

**Issue by 3CE8D2BAC65BDD6AA9** [cracker0dks/whiteboard#78]
First of all, thank you for the effort.  It is the best opensource whiteboard I have ever seen!

Do you have any documentations for integrating with Jitsi?

**Comment by cracker0dks** [comment]
unfortunately not, never tried that.

**Comment by Mattegray** [comment]
Is there a way to embed your whiteboard in an iFrame? If so, how will I be able to do that?

**Comment by cracker0dks** [comment]
Sure, fist you need to set up the whiteboard and then do this:
````
<iframe id="ifm" src="https://yourdomain.com/whiteboard/?whiteboardid=myid&amp;username=myusername" allowfullscreen=""></iframe>
````
This is how nextcloud does it.

**Comment by Mattegray** [comment]
Hi! How can I change the port number 8080 to something else? I am running into an error when running `npm run start:prod`.

**Comment by sammrafi** [comment]
Okay In this case.First setup the whiteboard as service and then add `<iframe id="ifm" src="https://yourdomain.com/whiteboard/?whiteboardid=myid&username=myusername" allowfullscreen=""></iframe>` as @cracker0dks provide in here 

the location path is 
for ubuntu/linux  => /usr/share/jitsi-meet/plugin.head.html

For docker first you have to enter in your docker service_web
then path is => /usr/share/jitsi-meet/plugin.head.html

then restart the docker service_web

or make sure it's position absolute because position relative can't show this and z-index make higher min 999
