### ISSUE TITLE
Add a paint/fill tool option?

### ISSUE THREAD

**Issue by spiral6** [cracker0dks/whiteboard#9]
Something that fills in a lined shape?

**Comment by cracker0dks** [comment]
I added this to a new branch: test_bucketfilltool so you can test it.
The problem here is, that pixel manipulation on a large canvas (areas) do not performe very well. So it is to slow to add this in the current state. 
I looked around, but didn't find a faster implementation then mine on the net. I will not include this feature to the main branch until we find a way faster solution, sry.
